name: Build Package (ARM64 and x86)

on:
  push:
    branches:
      - main

jobs:
  build_arm:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.77.1
        override: true

    - name: Ubuntu version 
      run: lsb_release -a

    - name: rustfmt
      run: rustup component add rustfmt

    - name: Install cargo-deb
      run: cargo install cargo-deb --no-default-features
    
    - name: Cache cargo build
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: false 
        cache-all-crates: true

    - name: Build Rust project
      env:
        PACKAGES: "chacha_poly"
      run: |
        for package in $PACKAGES; do
          cargo build --package $package --release
        done

    - name: Create Debian package
      run: cargo deb --no-build --deb-version 1.0.$GITHUB_RUN_NUMBER --no-strip -p chacha_poly
      
    - name: List Deb files
      run: | 
         find .

    - name: Upload to bunny
      env: 
          STORAGE_API_KEY: ${{ secrets.BUNNYCDN_STORAGE_API_KEY }}
          ZONE_API_KEY: ${{ secrets.BUNNYCDN_ZONE_API_KEY }}
          ZONE_ID: ${{ secrets.BUNNYCDN_DEV_ZONE_ID }}
          STORAGE_NAME: ${{ secrets.BUNNYCDN_STORAGE_NAME }}
      run: | 
          cd target/debian
          curl -s --request PUT --header "AccessKey: $STORAGE_API_KEY" -T ./*.deb "https://storage.bunnycdn.com/$STORAGE_NAME/"
          curl -s --request POST --header "AccessKey: $ZONE_API_KEY" --header "Content-Type: application/json" --header "Accept: application/json" "https://bunnycdn.com/api/pullzone/$ZONE_ID/purgeCache" --data "{"id":"$ZONE_ID"}"
  
  build_x86:
    runs-on: buildjet-4vcpu-ubuntu-2204

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.77.1
        override: true

    - name: Ubuntu version 
      run: lsb_release -a

    - name: rustfmt
      run: rustup component add rustfmt

    - name: Install cargo-deb
      run: cargo install cargo-deb --no-default-features
    
    - name: Cache cargo build
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: false 
        cache-all-crates: true

    - name: Build Rust project
      env:
        PACKAGES: "chacha_poly"
      run: |
        for package in $PACKAGES; do
          cargo build --package $package --release
        done

    - name: Create Debian package
      run: cargo deb --no-build --deb-version 1.0.$GITHUB_RUN_NUMBER --no-strip -p chacha_poly
      
    - name: List deb files
      run: | 
         find .

    - name: Upload to bunny
      env: 
          STORAGE_API_KEY: ${{ secrets.BUNNYCDN_STORAGE_API_KEY }}
          ZONE_API_KEY: ${{ secrets.BUNNYCDN_ZONE_API_KEY }}
          ZONE_ID: ${{ secrets.BUNNYCDN_DEV_ZONE_ID }}
          STORAGE_NAME: ${{ secrets.BUNNYCDN_STORAGE_NAME }}
      run: | 
          cd target/debian
          curl -s --request PUT --header "AccessKey: $STORAGE_API_KEY" -T ./*.deb "https://storage.bunnycdn.com/$STORAGE_NAME/"
          curl -s --request POST --header "AccessKey: $ZONE_API_KEY" --header "Content-Type: application/json" --header "Accept: application/json" "https://bunnycdn.com/api/pullzone/$ZONE_ID/purgeCache" --data "{"id":"$ZONE_ID"}"
